[MergeCoin]
computationCost = 503
storageCost = 0
storageRebate = 0

[Publish]
computationCost = 566
storageCost = 84
storageRebate = 0

[SharedCounterAssertValue]
computationCost = 188
storageCost = 31
storageRebate = 15

[SharedCounterCreate]
computationCost = 99
storageCost = 31
storageRebate = 0

[SharedCounterIncrement]
computationCost = 188
storageCost = 31
storageRebate = 15

[SplitCoin]
computationCost = 488
storageCost = 0
storageRebate = 0

[TransferPortionSuiCoin]
computationCost = 45
storageCost = 48
storageRebate = 0

[TransferWholeCoin]
computationCost = 41
storageCost = 32
storageRebate = 0

[TransferWholeSuiCoin]
computationCost = 38
storageCost = 32
storageRebate = 0
